// Code generated by protoc-gen-go. DO NOT EDIT.
// source: frequency.proto

package protobuf

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PageWordFrequency struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PageUrl              string   `protobuf:"bytes,2,opt,name=page_url,json=pageUrl,proto3" json:"page_url,omitempty"`
	PageTitle            string   `protobuf:"bytes,3,opt,name=page_title,json=pageTitle,proto3" json:"page_title,omitempty"`
	Words                []*Word  `protobuf:"bytes,4,rep,name=words,proto3" json:"words,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PageWordFrequency) Reset()         { *m = PageWordFrequency{} }
func (m *PageWordFrequency) String() string { return proto.CompactTextString(m) }
func (*PageWordFrequency) ProtoMessage()    {}
func (*PageWordFrequency) Descriptor() ([]byte, []int) {
	return fileDescriptor_717812b2e414acee, []int{0}
}

func (m *PageWordFrequency) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PageWordFrequency.Unmarshal(m, b)
}
func (m *PageWordFrequency) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PageWordFrequency.Marshal(b, m, deterministic)
}
func (m *PageWordFrequency) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PageWordFrequency.Merge(m, src)
}
func (m *PageWordFrequency) XXX_Size() int {
	return xxx_messageInfo_PageWordFrequency.Size(m)
}
func (m *PageWordFrequency) XXX_DiscardUnknown() {
	xxx_messageInfo_PageWordFrequency.DiscardUnknown(m)
}

var xxx_messageInfo_PageWordFrequency proto.InternalMessageInfo

func (m *PageWordFrequency) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PageWordFrequency) GetPageUrl() string {
	if m != nil {
		return m.PageUrl
	}
	return ""
}

func (m *PageWordFrequency) GetPageTitle() string {
	if m != nil {
		return m.PageTitle
	}
	return ""
}

func (m *PageWordFrequency) GetWords() []*Word {
	if m != nil {
		return m.Words
	}
	return nil
}

type Word struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Count                int32    `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Word) Reset()         { *m = Word{} }
func (m *Word) String() string { return proto.CompactTextString(m) }
func (*Word) ProtoMessage()    {}
func (*Word) Descriptor() ([]byte, []int) {
	return fileDescriptor_717812b2e414acee, []int{1}
}

func (m *Word) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Word.Unmarshal(m, b)
}
func (m *Word) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Word.Marshal(b, m, deterministic)
}
func (m *Word) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Word.Merge(m, src)
}
func (m *Word) XXX_Size() int {
	return xxx_messageInfo_Word.Size(m)
}
func (m *Word) XXX_DiscardUnknown() {
	xxx_messageInfo_Word.DiscardUnknown(m)
}

var xxx_messageInfo_Word proto.InternalMessageInfo

func (m *Word) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Word) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *Word) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type Response struct {
	Created              bool               `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
	PageWordFreq         *PageWordFrequency `protobuf:"bytes,2,opt,name=pageWordFreq,proto3" json:"pageWordFreq,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_717812b2e414acee, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCreated() bool {
	if m != nil {
		return m.Created
	}
	return false
}

func (m *Response) GetPageWordFreq() *PageWordFrequency {
	if m != nil {
		return m.PageWordFreq
	}
	return nil
}

func init() {
	proto.RegisterType((*PageWordFrequency)(nil), "protobuf.PageWordFrequency")
	proto.RegisterType((*Word)(nil), "protobuf.Word")
	proto.RegisterType((*Response)(nil), "protobuf.Response")
}

func init() { proto.RegisterFile("frequency.proto", fileDescriptor_717812b2e414acee) }

var fileDescriptor_717812b2e414acee = []byte{
	// 263 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0xc1, 0x4b, 0xc3, 0x30,
	0x14, 0xc6, 0x6d, 0xb7, 0xba, 0xee, 0x4d, 0x26, 0x3e, 0x06, 0x46, 0x45, 0x18, 0xc5, 0xc3, 0x4e,
	0x3d, 0xd4, 0x3f, 0x40, 0x50, 0xf0, 0xe4, 0x41, 0xa2, 0xe2, 0x51, 0xba, 0xe6, 0x6d, 0x14, 0x4a,
	0x53, 0xd3, 0x64, 0xe2, 0xd9, 0x7f, 0x5c, 0x92, 0x1a, 0x66, 0x29, 0xec, 0x14, 0xbe, 0xef, 0x4b,
	0xbe, 0xdf, 0xcb, 0x83, 0xd3, 0x8d, 0xa2, 0x4f, 0x43, 0x75, 0xf1, 0x9d, 0x36, 0x4a, 0x6a, 0x89,
	0xb1, 0x3b, 0xd6, 0x66, 0x93, 0xfc, 0x04, 0x70, 0xf6, 0x9c, 0x6f, 0xe9, 0x5d, 0x2a, 0xf1, 0xe8,
	0x6f, 0xe1, 0x1c, 0xc2, 0x52, 0xb0, 0x60, 0x19, 0xac, 0xa6, 0x3c, 0x2c, 0x05, 0x5e, 0x40, 0xdc,
	0xe4, 0x5b, 0xfa, 0x30, 0xaa, 0x62, 0xa1, 0x73, 0x27, 0x56, 0xbf, 0xa9, 0x0a, 0xaf, 0x01, 0x5c,
	0xa4, 0x4b, 0x5d, 0x11, 0x1b, 0xb9, 0x70, 0x6a, 0x9d, 0x57, 0x6b, 0xe0, 0x0d, 0x44, 0x5f, 0x52,
	0x89, 0x96, 0x8d, 0x97, 0xa3, 0xd5, 0x2c, 0x9b, 0xa7, 0x9e, 0x9c, 0x5a, 0x22, 0xef, 0xc2, 0xe4,
	0x1e, 0xc6, 0x56, 0x0e, 0xb8, 0x0b, 0x88, 0x76, 0x79, 0x65, 0xe8, 0x0f, 0xda, 0x09, 0xeb, 0x16,
	0xd2, 0xd4, 0xda, 0xd1, 0x22, 0xde, 0x89, 0x84, 0x20, 0xe6, 0xd4, 0x36, 0xb2, 0x6e, 0x09, 0x19,
	0x4c, 0x0a, 0x45, 0xb9, 0xa6, 0xae, 0x2c, 0xe6, 0x5e, 0xe2, 0x1d, 0x9c, 0x34, 0xff, 0xbe, 0xeb,
	0x8a, 0x67, 0xd9, 0xd5, 0x7e, 0xac, 0xc1, 0x32, 0x78, 0xef, 0x41, 0x26, 0x60, 0xd1, 0x8b, 0x5f,
	0x48, 0xed, 0xca, 0x82, 0xf0, 0x09, 0xce, 0x1f, 0x1c, 0x63, 0xb8, 0xcd, 0x43, 0xed, 0x97, 0xb8,
	0x0f, 0xfd, 0xf8, 0xc9, 0xd1, 0xfa, 0xd8, 0x99, 0xb7, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x4a,
	0x2b, 0xe8, 0xf8, 0xba, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// WordFrequencyServiceClient is the client API for WordFrequencyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WordFrequencyServiceClient interface {
	CreatePageWordFrequency(ctx context.Context, in *PageWordFrequency, opts ...grpc.CallOption) (*Response, error)
}

type wordFrequencyServiceClient struct {
	cc *grpc.ClientConn
}

func NewWordFrequencyServiceClient(cc *grpc.ClientConn) WordFrequencyServiceClient {
	return &wordFrequencyServiceClient{cc}
}

func (c *wordFrequencyServiceClient) CreatePageWordFrequency(ctx context.Context, in *PageWordFrequency, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/protobuf.WordFrequencyService/CreatePageWordFrequency", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WordFrequencyServiceServer is the server API for WordFrequencyService service.
type WordFrequencyServiceServer interface {
	CreatePageWordFrequency(context.Context, *PageWordFrequency) (*Response, error)
}

// UnimplementedWordFrequencyServiceServer can be embedded to have forward compatible implementations.
type UnimplementedWordFrequencyServiceServer struct {
}

func (*UnimplementedWordFrequencyServiceServer) CreatePageWordFrequency(ctx context.Context, req *PageWordFrequency) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePageWordFrequency not implemented")
}

func RegisterWordFrequencyServiceServer(s *grpc.Server, srv WordFrequencyServiceServer) {
	s.RegisterService(&_WordFrequencyService_serviceDesc, srv)
}

func _WordFrequencyService_CreatePageWordFrequency_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PageWordFrequency)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WordFrequencyServiceServer).CreatePageWordFrequency(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.WordFrequencyService/CreatePageWordFrequency",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WordFrequencyServiceServer).CreatePageWordFrequency(ctx, req.(*PageWordFrequency))
	}
	return interceptor(ctx, in, info, handler)
}

var _WordFrequencyService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.WordFrequencyService",
	HandlerType: (*WordFrequencyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePageWordFrequency",
			Handler:    _WordFrequencyService_CreatePageWordFrequency_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "frequency.proto",
}
